
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###
# Estão configuradas as contas registradas no arquivo insert_records.sql
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "206ef9f0-e240-4281-a4c8-6813e4f88861",
  "account_id_to": "3a2413c4-230a-4254-8744-f88764ad4b9a",
  "amount": 50
}